
CREATE TABLE Pembayaran(
PaymentID CHAR(5) PRIMARY KEY CHECK (PaymentID LIKE 'PY[0-9][0-9][0-9]') NOT NULL,
OrderID CHAR(5) FOREIGN KEY REFERENCES Orderr(OrderID) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,,
TanggalBayar DATE NOT NULL,
TotalBayar INT NOT NULL
)


